name: Yolo
main: io.github.KoenMulder.Yolo.Yolo
version: 1.0
commands:
  yolo:
    description: yolo
  wild:
    description: random location
  ip:
    description: ip 
  hashtag:
    description: instagram
  deathwish:
    description: prepare to die
  godspeed:
    description: can you handle the powers of the gods?